apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: swiggy-app
  name: swiggy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      containers:
      - image: laxg66/swiggy:latest
        name: swiggy
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: swiggy-app
  labels:
    app: swiggy-app
spec:
  type: nodePort
  ports:
  - port: 80
    targetPort: 3000
    NodePort: 30070
  selector:
    app: swiggy-app
